### ISSUE TITLE
'Dot' object is not iterable

### ISSUE THREAD

**Issue by rabbithui** [longcw/pytorch2caffe#14]
I run "demo.py" ,and got the error message as follows:
Traceback (most recent call last):
  File "/home/software/pycharm/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/software/pycharm/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/RNN/crnn.pytorch-master_demo/demo_caffe.py", line 50, in <module>
    plot_graph(output_var, os.path.join(caffemodel_dir, 'pytorch_graph.dot'))
  File "/home/RNN/crnn.pytorch-master_demo/pytorch2caffe.py", line 380, in plot_graph
    (graph,) = pydot.graph_from_dot_file(fname)
TypeError: 'Dot' object is not iterable

**Comment by hkchengrex** [comment]
For reference, I solved it by installing a newer version of pydot:

` sudo pip install -I pydot==1.2.4`
