### ISSUE TITLE
AttributeError:  tuple object has no attribute 'grad_fn'

### ISSUE THREAD

**Issue by dzyjjpy** [longcw/pytorch2caffe#27]
I want to convert pytorch model(hopenet) to caffemodel, However, met the following error:
**AttributeError: 'tuple' object has no attribute 'grad_fn'**
model want to convert:    [](https://github.com/natanielruiz/deep-head-pose)
pytorch: 0.2.0 
torchvision:0.1.8

And hopenet's  forward function will return more than one tensor:
    **return yaw, pitch, roll # all are 1*66's tensor**
**Might need to feed more than one tensor to output_var, but tuple has no attribute 'grad_fn'.**
I try to edit the return value, just return one value, e.g. yaw, it can works, but has errors with size mismatching.

Dose anyone have similar error? Suggesstions needed. Thank you so much.

**Comment by zhaobaozi** [comment]
have you finish?I meet the same problem

**Comment by trohit920** [comment]
@dzyjjpy @zhaobaozi @longcw Any updates on this ?

**Comment by dzyjjpy** [comment]
output has three branch 3*66, so you should edit the code in pytorch2caffe
convert_layer(output_var[0].grad_fn)
convert_layer(output_var[1].grad_fn)
convert_layer(output_var[2].grad_fn)
**as tuple object has no attribute 'grad_fn'**

**Comment by trohit920** [comment]
@dzyjjpy @zhaobaozi I did what you advised but got stuck with this error. 

```
  File "pytorch2caffe.py", line 428, in <module>
    os.path.join(output_dir, 'hopenet-pytorch2caffe.caffemodel'))
  File "pytorch2caffe.py", line 38, in pytorch2caffe
    net_info = pytorch2prototxt(input_var, output_var)
  File "pytorch2caffe.py", line 330, in pytorch2prototxt
    add_layer(output_var[0].grad_fn)
  File "pytorch2caffe.py", line 157, in add_layer
    top_name = add_layer(u[0])
  File "pytorch2caffe.py", line 169, in add_layer
    layer['type'] = layer_dict[parent_type]
KeyError: 'ExpandBackward'
```
I am a newbie, hope you can understand. Can you share the converted caffe model if possible ?

**Comment by trohit920** [comment]
@dzyjjpy I have solved the above error by changing to pytorch0.2. However i encountered another error like this:

```
I0603 10:45:21.869765  8625 net.cpp:86] Creating Layer AvgPool2dBackward189_AvgPool2dBackward189_0_split
I0603 10:45:21.869769  8625 net.cpp:408] AvgPool2dBackward189_AvgPool2dBackward189_0_split <- AvgPool2dBackward189
I0603 10:45:21.869776  8625 net.cpp:382] AvgPool2dBackward189_AvgPool2dBackward189_0_split -> AvgPool2dBackward189_AvgPool2dBackward189_0_split_0
I0603 10:45:21.869781  8625 net.cpp:382] AvgPool2dBackward189_AvgPool2dBackward189_0_split -> AvgPool2dBackward189_AvgPool2dBackward189_0_split_1
I0603 10:45:21.869787  8625 net.cpp:382] AvgPool2dBackward189_AvgPool2dBackward189_0_split -> AvgPool2dBackward189_AvgPool2dBackward189_0_split_2
I0603 10:45:21.869793  8625 net.cpp:124] Setting up AvgPool2dBackward189_AvgPool2dBackward189_0_split
I0603 10:45:21.869797  8625 net.cpp:131] Top shape: 1 2048 2 2 (8192)
I0603 10:45:21.869801  8625 net.cpp:131] Top shape: 1 2048 2 2 (8192)
I0603 10:45:21.869805  8625 net.cpp:131] Top shape: 1 2048 2 2 (8192)
I0603 10:45:21.869808  8625 net.cpp:139] Memory required for data: 259040000
I0603 10:45:21.869812  8625 layer_factory.hpp:77] Creating layer AddmmBackward190
I0603 10:45:21.869817  8625 net.cpp:86] Creating Layer AddmmBackward190
I0603 10:45:21.869819  8625 net.cpp:408] AddmmBackward190 <- AvgPool2dBackward189_AvgPool2dBackward189_0_split_0
I0603 10:45:21.869825  8625 net.cpp:382] AddmmBackward190 -> AddmmBackward190
I0603 10:45:21.870537  8625 net.cpp:124] Setting up AddmmBackward190
I0603 10:45:21.870543  8625 net.cpp:131] Top shape: 1 66 (66)
I0603 10:45:21.870546  8625 net.cpp:139] Memory required for data: 259040264
I0603 10:45:21.870551  8625 layer_factory.hpp:77] Creating layer AddmmBackward190
I0603 10:45:21.870556  8625 net.cpp:86] Creating Layer AddmmBackward190
I0603 10:45:21.870559  8625 net.cpp:408] AddmmBackward190 <- AvgPool2dBackward189_AvgPool2dBackward189_0_split_1
F0603 10:45:21.870566  8625 net.cpp:377] Top blob 'AddmmBackward190' produced by multiple sources.
*** Check failure stack trace: ***
Aborted (core dumped)
```
Did you face this problem? I checked the generated prototxt file and AddmmBackward190 is produced 3 times. I am not sure how to remove this error. Any help will be hugely appreciated. Thanks in advance.

**Comment by trohit920** [comment]
@dzyjjpy I have solved all the previous errors and stuck with this one: 

```
converting AddmmBackward190
((66L,), (66L, 2048L))
(66,)
(66, 8192)
Traceback (most recent call last):
  File "pytorch2caffe.py", line 441, in <module>
    os.path.join(output_dir, 'hopenet-pytorch2caffe.caffemodel'))
  File "pytorch2caffe.py", line 99, in pytorch2caffe
    convert_layer(output_var[0].grad_fn)
  File "pytorch2caffe.py", line 94, in convert_layer
    save_fc2caffe(weights, biases, params[parent_name])
  File "pytorch2caffe.py", line 118, in save_fc2caffe
    fc_param[0].data[...] = weights.numpy()
ValueError: could not broadcast input array from shape (66,2048) into shape (66,8192)
```
Please if you know how to convert any advice will be helpful.

**Comment by dzyjjpy** [comment]
shape issue, pay attention to your tensor size. there might be issue caused by pooling layer's calculation mode.   floor or ceil. pls check the layer with errors carefully
