### ISSUE TITLE
convert KeyError: 'MkldnnConvolutionBackward'

### ISSUE THREAD

**Issue by yueyihua** [longcw/pytorch2caffe#35]
[root@greenet tools]# python torch2caffe.py 
Traceback (most recent call last):
  File "torch2caffe.py", line 29, in <module>
    pytorch2caffe(input_var, output_var, './tc-pytorch2caffe.prototxt', './tc-pytorch2caffe.caffemodel')
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 37, in pytorch2caffe
    net_info = pytorch2prototxt(input_var, output_var)
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 325, in pytorch2prototxt
    add_layer(output_var.grad_fn)
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 153, in add_layer
    top_name = add_layer(u[0])
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 153, in add_layer
    top_name = add_layer(u[0])
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 153, in add_layer
    top_name = add_layer(u[0])
  [Previous line repeated 58 more times]
  File "/home/yyh/tools/pytorch2caffe/pytorch2caffe.py", line 165, in add_layer
    layer['type'] = layer_dict[parent_type]
KeyError: 'MkldnnConvolutionBackward'

**Comment by yueyihua** [comment]
The same as #25
