### ISSUE TITLE
KeyError: 'ExpandBackward'

### ISSUE THREAD

**Issue by lastlaugher** [longcw/pytorch2caffe#6]
I tried "python pytorch2caffe" and I've got below error message.

> Traceback (most recent call last):
  File "pytorch2caffe.py", line 408, in <module>
    os.path.join(output_dir, 'inception_v3-pytorch2caffe.caffemodel'))
  File "pytorch2caffe.py", line 37, in pytorch2caffe
    net_info = pytorch2prototxt(input_var, output_var)
  File "pytorch2caffe.py", line 328, in pytorch2prototxt
    add_layer(output_var.grad_fn)
  File "pytorch2caffe.py", line 154, in add_layer
    top_name = add_layer(u[0])
  File "pytorch2caffe.py", line 168, in add_layer
    layer['type'] = layer_dict[parent_type]
KeyError: 'ExpandBackward'

My pytorch version is the latest one, http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl

**Comment by xuzijian** [comment]
I have met same problems. I guess the conversion code has not support 'ExpandBackward' currently.

**Comment by jnulzl** [comment]
met same problems too!

**Comment by wangxc2006** [comment]
same problem， can anybody give some tips？

**Comment by lzhaozi** [comment]
met same problems too!

**Comment by autocyz** [comment]
Let pytorch=0.2, torchvision=0.1.8, the problem will be solved! 
I don't kown why, maybe newer pytorch use 'ExpandBackward' to name layer, but older pytorch do not use. And the `layer_dict` in `pytorch2caffe.py` do not have  'ExpandBackward'

**Comment by wyfdodogod** [comment]
does that mean any model trained in torch version 3 and above need to be retrained in torch 2 and then safe to be converted to caffe

**Comment by autocyz** [comment]
@wyfdodogod  I think you needn't retrain in torch 2,  you should understand the meaning of  `ExpandBackward`  and add this key to [layer_dict](https://github.com/longcw/pytorch2caffe/blob/master/pytorch2caffe.py#L14) , then you should add some operater in function [pytorch2prototxt](https://github.com/longcw/pytorch2caffe/blob/master/pytorch2caffe.py#L77), just like [elif parent_type == 'BatchNormBackward':](https://github.com/longcw/pytorch2caffe/blob/master/pytorch2caffe.py#L77)

**Comment by wyfdodogod** [comment]
@autocyz ty for the explaination, as you mentioned using torch 0.2 and torchvision 0.1.8, i solved the problem more specifically torch0.2 post1 using post2 and 3 might raise error causing python crash at the time caffe is imported.

**Comment by ys198918** [comment]
@wangxc2006  did you retrain the model under torch 0.2?

**Comment by elepherai** [comment]
Any plan to support 0.4.x ?

**Comment by dzyjjpy** [comment]
@autocyz @longcw met same issue when running demo.py.
when i try to install 0,2.0 by pip install torch==0.2.0 or pip isntall torch-0.2.0.post********.whl
(I  try install it based CUDA 9.2 or CUDA 8.0)
errors displays:
        is not a supported wheel on this platform
so strange. dose anyone run demo,py sucessfully  on torch==0.3.1 and torchvision==0.2.0
I trained model on the env above. thanks

**Comment by konioyxgq** [comment]
@autocyz Like you said, "should understand the meaning of ExpandBackward and add this key to layer_dict , then you should add some operater in function pytorch2prototxt, just like elif parent_type == 'BatchNormBackward':"
But i don't know ‘ExpandBackward’ means. So how should it be modified?
